title: Dorian - een online dagboek van Simeon Duwel
email: tameimpalafan123@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Een online dagboek van Simeon Duwel; geobscureerd en onzichtbaar voor
  het publieke oog, dus. Als je dit aan het lezen bent, ben je oftewel
  ikzelf oftewel iemand die ik heel erg vertrouw.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: simeondermaats
github_username:  WalrusGumboot

# Build settings
theme: minima

plugins:
  - jekyll-feed

minima:
  skin: dark

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
